#!/bin/bash

# adjust start() and stop() to your needs
# and replace path to local copy of this repo below
apache-certbot-path=<path-to-apache-certbot-folder>

ERRNO=0

dk_stop(){
  sudo docker-compose -f "$1" stop
}
dk_start(){
  sudo docker-compose -f "$1" up -d
}

stop(){
  dk_stop <path_to_docker-compose.yml_1>
  dk_stop <path_to_docker-compose.yml_2>
}

start(){
  dk_start <paht_to_docker-compose.yml_1>
  dk_start <paht_to_docker-compose.yml_1>
}

echo "Stop all docker containers"
stop

if [ "$(sudo docker ps | wc -l)" -ne "1" ]
then
  echo "Seems like there are still some docker containers running!"
  echo "Won't try to renew certificates"
  start
  exit 1
fi

sudo docker-compose -f "$pache-certbot-path"/docker-compose.yml build && \
sudo docker-compose -f "$pache-certbot-path"/docker-compose.yml up

if [ "$?" -ne "0" ]
then
  ERRNO=1
fi

start

if [ "$?" -ne "0" ]
then
  ERRNO=1
fi

exit "$ERRNO"
